replicaCount: 1

namespace: websvc

image:
  repository: "metairie/websvc"
  pullPolicy: IfNotPresent
  tag: "0.0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: false

services:
  type: ClusterIP
  svc:
    - name: websvc
      port: 8000
      targetport: 8000
      protocol: TCP
      nodeport: 


resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}